# Site settings
title: "Martin Fowler's Bliki (ja)"
email: kdmsnr AT gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bliki-ja.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  bliki-ja

timezone: Asia/Tokyo

permalink: :title
exclude: [Rakefile, README.md]

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [autolink,strikethrough,footnotes,tables]

